M48
; DRILL file {KiCad 9.0.7} date 2026-02-12T14:24:54+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-12T14:24:54+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X122.175Y-78.475
X122.175Y-85.475
T2
X78.45Y-115.65
X78.5Y-77.2
X133.4Y-115.05
X194.925Y-77.175
X194.95Y-115.65
M30
